### ISSUE TITLE
Why is the opt step inside the forward pass?

### ISSUE THREAD

**Issue by VictorZuanazzi** [stevenygd/PointFlow#10]
https://github.com/stevenygd/PointFlow/blob/e15a9ccd030990e25df64ecd583680d2c7d0f3c9/models/networks.py#L168

Congrats for the work. I was just wondering if there is a reason for the opt.step() to be inside the forward pass of the PointFlow. Is that necessary?

**Comment by stevenygd** [comment]
Nope, that's just the artifact of naming .
