### ISSUE TITLE
ModuleNotFoundError: No module named 'metrics.StructuralLosses'

### ISSUE THREAD

**Issue by leno0903** [stevenygd/PointFlow#12]
File "train.py", line 273, in <module>
    main()
  File "train.py", line 269, in main
    main_worker(args.gpu, save_dir, ngpus_per_node, args)
  File "train.py", line 192, in main_worker
    validate(test_loader, model, epoch, writer, save_dir, args, clf_loaders=clf_loaders)
  File "/home/leon/a312/xhs/point-cloud/PointFlow/utils.py", line 372, in validate
    save_dir=save_dir)
  File "/home/leon/a312/xhs/point-cloud/PointFlow/utils.py", line 211, in validate_conditioned
    from metrics.evaluation_metrics import EMD_CD
  File "/home/leon/a312/xhs/point-cloud/PointFlow/metrics/evaluation_metrics.py", line 9, in <module>
    from .pytorch_structural_losses.match_cost import match_cost
  File "/home/leon/a312/xhs/point-cloud/PointFlow/metrics/pytorch_structural_losses/match_cost.py", line 3, in <module>
    from metrics.StructuralLosses.StructuralLossesBackend import ApproxMatch, MatchCost, MatchCostGrad
ModuleNotFoundError: No module named 'metrics.StructuralLosses'

**Comment by AntheaLi** [comment]
I have the same issue. Tried building the metrics with pytorch1.0.1, pytorch1.3.1, pytorch1.4.0. and None of them works.

**Comment by leno0903** [comment]
I solved this problem&nbsp;my env:pytorch1.0.1, cuda10.0
your problem maybe enviroment's probelm,
please check your env




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AntheaLi"<notifications@github.com&gt;; 
发送时间: 2020年7月7日(星期二) 上午9:24
收件人: "stevenygd/PointFlow"<PointFlow@noreply.github.com&gt;; 
抄送: "497208386"<497208386@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [stevenygd/PointFlow] ModuleNotFoundError: No module named &#39;metrics.StructuralLosses&#39; (#12)





 
I have the same issue. Tried building the metrics with pytorch1.0.1, pytorch1.3.1, pytorch1.4.0. and None of them works.

**Comment by stevenygd** [comment]
This is because the evaluation losses aren't compiled successfully. Try to check your environment and fix the compilation error.

**Comment by leno0903** [comment]
many thanks
