### ISSUE TITLE
Test results with pre-trained donot match what shows in the paper

### ISSUE THREAD

**Issue by lmy1001** [stevenygd/PointFlow#13]
Hi, I tried to test the PointFlow with the pre-trained model you provided, and tested it on the airplane test data for generation performance,  what i got, for example, JSD:0.05163973286326318, but in your paper it's 0.0492. Is there anything I miss?

**Comment by stevenygd** [comment]
How did you obtain this results? Is it due to the variance between runs?

**Comment by stevenygd** [comment]
I would suggest using the following script to obtain the test result: https://github.com/stevenygd/PointFlow/blob/master/scripts/shapenet_airplane_gen_test.sh.

**Comment by lmy1001** [comment]
> How did you obtain this results? Is it due to the variance between runs?

Yes, I obtained the results by running shapenet_airplane_gen_test.sh.
