### ISSUE TITLE
reshape in MovingBatchNormNd?

### ISSUE THREAD

**Issue by panzhang0212** [stevenygd/PointFlow#14]
https://github.com/stevenygd/PointFlow/blob/33ce21ff8c42e1c58949742999618fc114e25b86/models/normalization.py#L53
the shape:
x: 16\*2048\*3,
x.transpose(0, 1): 2048\*16\*3
x.transpose(0, 1).reshape(num_channels, -1) : 3\*32768

should it be x.transpose(1, 2).transpose(0, 1).reshape(num_channels, -1)?

**Comment by stevenygd** [comment]
The batch normalization layer assum the input is (bs, num_channel)
https://github.com/stevenygd/PointFlow/blob/33ce21ff8c42e1c58949742999618fc114e25b86/models/normalization.py#L140

So when inputting into this, we should reshape the tensor input (bs x #points, dim)
