### ISSUE TITLE
Varying #samples during training and test time

### ISSUE THREAD

**Issue by xchhuang** [stevenygd/PointFlow#16]
Hi, thank you for releasing the code.

I ran the airplane experiments and found that the number of samples of each shape (`tr_max_sample_points in args.py`) is set to be 2048. Is it possible to vary the number of samples during training with the same network ? Or it just means maximum points and we can handle shape with fewer points by padding zeros ? 

I am also wondering if it's possible to reconstruct more samples up to 4096 during test time after training on max. 2048 samples. Thanks in advance.

**Comment by stevenygd** [comment]
yes you can change the number of points sampled. The reason I fixed the number of sample points is for the convenience of batching (e.g. the tensor just need to be (batch_size, #sample_points, 3)) 

For test time, the number of samples output will be the same as the number of sampled in the noise. So if the noise is (batch_size, 4096, 3), the CNF will produce 4096 points.

Does this answer your question?

**Comment by xchhuang** [comment]
Hi, this makes sense. Thanks for your clarification.
