### ISSUE TITLE
ImportError: PointFlow/metrics/StructuralLosses/StructuralLossesBackend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

### ISSUE THREAD

**Issue by trung6** [stevenygd/PointFlow#18]
Hi, thank you for releasing the code.
I got this error when running `./scripts/shapenet_airplane_gen_test.sh`. 
Could you have any solution for this? 
Thanks in advance.

**Comment by stevenygd** [comment]
Seemed like the problem is that when you compile the test, it wasn't successful. When you run the `install.sh` script, did you see any error messages?

**Comment by trung6** [comment]
In file `install.sh`, I changed into c++14, pytorch=1.4.0, torchvision=0.5.0. It seems work well now. Thank you.
