### ISSUE TITLE
Pretrained Model on Chair Class

### ISSUE THREAD

**Issue by hughw19** [stevenygd/PointFlow#19]
Thanks for the great work!

Could you please also release the pretrained model on ShapeNet chair class? We need it for paper submission, so it would be great if you can release it as soon as possible.

**Comment by stevenygd** [comment]
It seemed like the pretrained model for ShapeNet chair is in https://drive.google.com/file/d/1dcxjuuKiAXZxhiyWD_o_7Owx8Y3FbRHG/view 
Were you able to get to it?
