### ISSUE TITLE
Cannot execute StructuralLosses 

### ISSUE THREAD

**Issue by YiruS** [stevenygd/PointFlow#2]
Hi,

Interesting work! I'd like to run the pipeline but it turns out that the installed "StructuredLosses" doesn't work. It shows error of:
"File "evaluation_metrics.py", line 9, in <module>
from .StructuralLosses.match_cost import match_cost
ModuleNotFoundError: No module named '__main__.StructuralLosses'; '__main__' is not a package"

Would that be a workaround?

**Comment by YiruS** [comment]
Somehow it couldn't detect the package

**Comment by stevenygd** [comment]
Seemed like this is the same problem as issue #1 . Could you check whether the structure losses are compiled successfully?

**Comment by stevenygd** [comment]
@YiruS any luck debugging?

**Comment by stevenygd** [comment]
Close due to inactiveness.
