### ISSUE TITLE
about loss

### ISSUE THREAD

**Issue by qianyewu** [stevenygd/PointFlow#24]
Hello, I would like to ask about the loss. I have been training for a long time, but the loss has always been large, which is maintained at about 30000.
Have I not been training long enough?Finally, after you've trained 15,000 EPOCHs, what is loss going to be？THANKS

**Comment by stevenygd** [comment]
The loss should behaves like first decrease exponentially then goes to an log decrease (i.e. if you sharing the time axis by log scale, then it will be linear). Did you see whether the loss decreases?
