### ISSUE TITLE
ModelNet10/40 datasets

### ISSUE THREAD

**Issue by titaniumrain** [stevenygd/PointFlow#28]
Hi Steven,

Thanks for sharing the PointFlow code. Per your instruction, we get in touch to understand the procedure to obtain ModelNet10/40 datasets. It is our understanding that Pytorch Geometric can download raw ModelNet data (.txt). May we please ask if you can share the code to preprocess raw data into numpy array?

Cheers,

V

**Comment by stevenygd** [comment]
Could you send me an email to request the ModelNet data? I can share it with you through email. 

At that time, my collaborator has a private repository that contains code to load mesh and sample surface point clouds. If you want that version , you can reach out to Zekun Hao (http://www.cs.cornell.edu/~zekun/). Right now I think you can also do the following:
```
import trimesh
trimesh.load_mesh(<mesh_path).sample(<number_of_points>)
```
