### ISSUE TITLE
Render animation

### ISSUE THREAD

**Issue by DeVriesMatt** [stevenygd/PointFlow#33]
Great repo, thank you! I have seen that you have another repo for rendering the point cloud for visualisation but cannot see how you created animations. Would it be possible to share this code too?

**Comment by stevenygd** [comment]
Does this repository help? https://github.com/zekunhao1995/PointFlowRenderer

**Comment by DeVriesMatt** [comment]
Hi @stevenygd , I meant code to generate something similar to [this](https://github.com/stevenygd/PointFlow/blob/master/docs/assets/teaser.gif)?

**Comment by zhanghm1995** [comment]
@DeVriesMatt, Have you found any ways to generate the gif similar to [this](https://github.com/stevenygd/PointFlow/blob/master/docs/assets/teaser.gif)?

**Comment by DeVriesMatt** [comment]
Hi @zhanghm1995, I have been adapting a repo to create sequential renders of multiple ".ply" files, combing the images, and saving them as a gif. Hope [this](https://github.com/DeVriesMatt/Mitsuba2PointCloudRenderer/blob/master/render_gif.py) helps!

**Comment by skylooop** [comment]
@DeVriesMatt Hi! I was wondering, whether you managed to find a solution? I looked at your code, however, there are no settings on how to create gif. My gifs are not as smooth as in teaser.gif provided by authors of this repo.
Thank you!

**Comment by DeVriesMatt** [comment]
@skylooop I still don't have a solution that is as smooth as the authors. I assume they saved many images and combined them to make it smooth. My (adapted) code only creates multiple images. To combine these in a gif, I used [fiji](https://fiji.sc/)
