### ISSUE TITLE
Point cloud to mesh 

### ISSUE THREAD

**Issue by Siziff** [stevenygd/PointFlow#35]
Hello:) I got a point cloud, but I don't know how to wrap it in a mesh, I tried a lot of methods, but they all turn out too not pretty (example in the picture). Do you know how to improve the point cloud to get a better mesh shape? or maybe you know cool algorithms for getting a beautiful mesh shape?
![image](https://user-images.githubusercontent.com/42972554/204809338-315a4149-5cc1-4730-9486-ec3d7db87cdf.png)

**Comment by stevenygd** [comment]
Perhaps some of the algorithms that performs MC on unsigned distance can be useful. For example:
https://github.com/RuojinCai/ShapeGF
https://www.semanticscholar.org/paper/Marching-Cubes-in-an-Unsigned-Distance-Field-for-Congote-Moreno/e70ed0678c0a5a680d759f9724e5128a0101c426
