### ISSUE TITLE
Makefile for CUDA 11

### ISSUE THREAD

**Issue by gopalkulkarni-123** [stevenygd/PointFlow#36]
Hello, 
I'm trying to compile the makefile for CUDA 11 but it doesn't seem to work. Could you please let me know how to proceed? The error it throws is as follows

mv: cannot stat 'build/lib.linux-x86_64-3.6/StructuralLosses': No such file or directory

Kindly let me know how to resolve this. Thanks

**Comment by gopalkulkarni-123** [comment]
It turns out that the script runs just fine for cuda 11 as well

**Comment by guangjinpan** [comment]
@gopalkulkarni-123 hi, can you tell me how to solve this problem? I have the same problem
