### ISSUE TITLE
The time spent on each epoch is increasing

### ISSUE THREAD

**Issue by Fly-Pluche** [stevenygd/PointFlow#41]
I added the flow block in the PointFlow to my model. Then, the bug happened.
I tried `torch.cuda.empty_cache()` and `del recon_loss` , but not work. 
![71aab4587a4534d74ded156788f4a94](https://github.com/stevenygd/PointFlow/assets/73021377/b14893a7-94e2-4d94-bcf2-10b827cef5dd)

**Comment by YTYang627** [comment]
> I added the flow block in the PointFlow to my model. Then, the bug happened. I tried `torch.cuda.empty_cache()` and `del recon_loss` , but not work. ![71aab4587a4534d74ded156788f4a94](https://private-user-images.githubusercontent.com/73021377/292676420-b14893a7-94e2-4d94-bcf2-10b827cef5dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MjU2MjEsIm5iZiI6MTcwODkyNTMyMSwicGF0aCI6Ii83MzAyMTM3Ny8yOTI2NzY0MjAtYjE0ODkzYTctOTRlMi00ZDk0LWJjZjItMTBiODI3Y2VmNWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA1Mjg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZjMxOWVlNTM4ZTBlZjEwYWMxYWY5ZTc2NjQ0MzgyMGU5OGYxYjUzY2IwNTJkOWZmNjlhMDE3YWNkZTQ0ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O5kPaMGsxFKddzN7HfYJtjAVGHDgQzJVSvtZr3dRmaY)

Have you solved this problem? I met the same problem.

**Comment by stevenygd** [comment]
Have you visualize the number of solver steps? It could be the server steps increasing as the training go, which can happen as the points flow in more and more curve trajectories.
