### ISSUE TITLE
How to generate ShapeNetCore.v2.PC15k file?

### ISSUE THREAD

**Issue by dqj5182** [stevenygd/PointFlow#42]
I can see that the file can be downloaded from the Google Drive link provided in this repository.
However, I wish to know how you generated such file.
Many of the ShapeNetCore meshes are 1) not watertight and 2) contains reversed mesh faces.
I wish to know 1) how you defined surface from such noisy meshes and 2) how you sampled point from the surface?

**Comment by stevenygd** [comment]
Point sampling from mesh can be done by most mesh libraries (we just sample uniformly). For inside/outside queries, you could shot rays from the points to figure it out.
