### ISSUE TITLE
Typo in flow model building ?

### ISSUE THREAD

**Issue by dawood95** [stevenygd/PointFlow#5]
https://github.com/stevenygd/PointFlow/blob/372215d42797ca062127f4bc4348d882136287b5/models/flow.py#L66

Should this be build_cnf?

**Comment by stevenygd** [comment]
Hi, thanks for being interested in our codebase! I think the line you are referring to is trying to create the batch normalization layers, so it seemed correct to me. Any particular reason you think this should be build_cnf?

**Comment by dawood95** [comment]
Nevermind, my bad. I misread line 69. Thanks for the quick reply!
